### PR TITLE
Fix: Do not use `static` in callables

### LINKED ISSUE #784: Warning DEPRECATED  use of static pt_BR PhoneNumber
image

DEPRECATED  Use of "static" in callables is deprecated in vendor/fakerphp/faker/src/Faker/Provider/pt_BR/PhoneNumber.php on line 138.

### PR DESCRIPTION
**Pull request by localheinz**
### What is the reason for this PR?

- [x] stops using `static` in callables 

Fixes #784.
Follows #479.

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)

### Review checklist

- [x] All checks have passed
- [x] Changes are added to the `CHANGELOG.md`
- [x] Changes are approved by maintainer

### CODE REVIEW

File: test/Faker/Provider/pt_BR/PhoneNumberTest.php [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+ * @covers \Faker\Provider\pt_BR\PhoneNumber
+ */
+final class PhoneNumberTest extends Test\TestCase
+{
+    public function testPhoneReturnsPhoneNumberWhenArgumentIsFalse(): void
+    {
+        $phoneNumber = $this->faker->phone(false);
+
+        self::assertIsString($phoneNumber);
+        self::assertNotEmpty($phoneNumber);
```
Comment (localheinz) [inline test/Faker/Provider/pt_BR/PhoneNumberTest.php:20]: These tests are not very useful other than letting us see whether we still trigger any deprecations here.

**Review by bram-pkg — APPROVED** [review]
LGTM, thanks @localheinz

**Comment by localheinz** [comment]
Thank you, @bram-pkg!
