### PR TITLE
Fix: Do not use deprecated `MT_RAND_PHP` constant on PHP 8.3

### LINKED ISSUE #694: Add support for PHP 8.3
In all likelihood, [PHP 8.3 will be released on November 23, 2023](https://wiki.php.net/todo/php83), and it would be great if we could support PHP 8.3 soon after the official release.

- [x] require tests to pass on PHP 8.3
    - see #693
    - see #844 
- [x] stop using `MT_RAND_PHP` constant deprecated on PHP 8.3
    - see https://github.com/php/php-src/pull/11560
    - see https://wiki.php.net/rfc/deprecations_php_8_3#mt_rand_php
    - see #844

### PR DESCRIPTION
**Pull request by localheinz**
### What is the reason for this PR?

- [x] requires tests to pass on PHP 8.3
- [x] stops using the deprecated `MT_RAND_PHP` constant on PHP 8.3 
- [x] skips tests failing on PHP 8.3 when running on PHP 8.3 and above

Fixes #694.

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Review checklist

- [x] All checks have passed
- [x] Changes are added to the `CHANGELOG.md`
- [ ] Changes are approved by maintainer

### CODE REVIEW

File: src/Faker/Generator.php [hunk 1]
```diff
@@ -687,10 +687,22 @@ public function seed($seed = null)
...
+            mt_srand((int) $seed, self::mode());
         }
     }
 
+    /**
+     * @see https://www.php.net/manual/en/migration83.deprecated.php#migration83.deprecated.random
+     */
+    private static function mode(): int
+    {
+        if (PHP_VERSION_ID < 80300) {
```
Comment (pimjansen) [inline src/Faker/Generator.php:699]: Bleghh 😋 but best way 👌🏻

**Review by pimjansen — APPROVED** [review]

**Comment by localheinz** [comment]
Thank you, @pimjansen!
