### PR TITLE
Prevent direct access and triggered deprecation warning for "word" me…

### LINKED ISSUE #298: randomHtml error
### Summary

$this->faker->randomHtml(2,3)
Error:
```
PHP Deprecated:  Since fakerphp/faker 1.14: Accessing property "word" is deprecated, use "word()" instead. in /Users/tina/Sites/jetstream/vendor/symfony/deprecation-contracts/function.php on line 25
```

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8  |
| `fakerphp/faker`  | 1.14.1   |

### Self-enclosed code snippet for reproduction

```php
$this->faker->randomHtml(2,3)
```

### PR DESCRIPTION
**Pull request by pimjansen**
### What is the reason for this PR?

Deprecation warnings are thrown from core methods while direct accessing properties which is not allowed anymore since 1.14

- [ ] A new feature
- [x] Fixed an issue (resolve #298)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

The internal methods now call the function instead of accessing the properties directly.

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

### CODE REVIEW

**Comment by tanthammar** [comment]
I think the safeEmailDomain also needs (), I got a lot of warnings about that to. Couldn't figure where it came from.

**Review by bramceulemans — APPROVED** [review]
lgtm!

File: src/Faker/Provider/HtmlLorem.php [hunk 1]
```diff
@@ -234,19 +234,19 @@ private function addLoginForm(\DOMElement $element)
...
-        $passwordLabel->textContent = $this->generator->word;
+        $passwordLabel->textContent = $this->generator->word();
 
         $submit = $element->ownerDocument->createElement(static::INPUT_TAG);
         $submit->setAttribute('type', 'submit');
-        $submit->setAttribute('value', $this->generator->word);
+        $submit->setAttribute('value', $this->generator->word());
 
         $submit = $element->ownerDocument->createElement(static::FORM_TAG);
         $submit->setAttribute('action', $this->generator->safeEmailDomain);
```
Comment (bramceulemans) [inline src/Faker/Provider/HtmlLorem.php:252]: Add method call here too, on `safeEmailDomain`?

**Review by bramceulemans — CHANGES_REQUESTED** [review]

File: src/Faker/Provider/HtmlLorem.php (hunk 1 above)
Comment (pimjansen) [reply src/Faker/Provider/HtmlLorem.php:252]: Yeah will review the core methods quickly to see what else we hit

**Review by bramceulemans — APPROVED** [review]
