### PR TITLE
fix #832

### LINKED ISSUE #832: [ru_RU/PersonProvider] Double `а` in female lastName when using the `name()` function
### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.3   |
| `fakerphp/faker`  | v1.23.0  |

### Self-enclosed code snippet for reproduction

```php
 $generator = Factory::create('ru_RU');
 $generator->seed(1917);
 self::assertSame('Павлова Нонна Александровна', $generator->name('female')); // this fails
```

image

TestCase
```php
 /**
     * @dataProvider dataIssue832
     */
    public function testIssue832(int $seed, string $expected): void
    {
        $generator = new Generator();
        $generator->seed($seed);

        foreach ($this->getProviders() as $provider) {
            $generator->addProvider($provider);
        }

        self::assertSame($expected, $generator->name('female'));
    }

    public static function dataIssue832(): iterable
    {
        //bad cases
        yield 'seed: 55' => [
            55,
            'Ларионова Алина Ивановна'
        ];
        yield 'seed: 512' => [
            512,
            'Тихонова Владлена Львовна'
        ];
        yield 'seed: 625' => [
            625,
            'Ларионова Нонна Максимовна'
        ];
        yield 'seed: 1917' => [
            1917,
            'Павлова Нонна Александровна'
        ];

        //good cases
        yield 'seed: 4' => [
            4,
            'Фаина Фёдоровна Романоваа'
        ];
        yield 'seed: 8' => [
            8,
            'Яна Александровна Жукова'
        ];
        yield 'seed: 42' => [
            42,
            'Гуляева Розалина Дмитриевна'
        ];
    }
```

### PR DESCRIPTION
**Pull request by gam6itko**
### What is the reason for this PR?

- [ ] A new feature
- [x] Fixed an issue (resolve #832)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

Fix ru_RU name() female lastNames

### Review checklist

- [x] All checks have passed
- [x] Changes are added to the `CHANGELOG.md`
- [x] Changes are approved by maintainer

### CODE REVIEW

**Comment by gam6itko** [comment]
I just tried the tests for Person on another machine, they pass successfully

**Review by davydovks — APPROVED** [review]

File: src/Faker/Generator.php [hunk 1]
```diff
@@ -451,7 +451,7 @@
  *
  * @property string $firstName
  *
- * @method string firstName($gender = null)
+ * @method string firstName(?string $gender = null)
```
Comment (pimjansen) [inline src/Faker/Generator.php]: Not relevant for this fix

File: src/Faker/Generator.php [hunk 2]
```diff
@@ -463,7 +463,7 @@
  *
  * @property string $lastName
  *
- * @method string lastName()
+ * @method string lastName(?string $gender = null)
```
Comment (pimjansen) [inline src/Faker/Generator.php]: Not relevant for this fix

File: test/Faker/Provider/ru_RU/PersonTest.php [hunk 3]
```diff
@@ -29,4 +30,135 @@ protected function getProviders(): iterable
...
+        yield 'seed: 42' => [
+            42,
+            'Горбачёва',
+        ];
+    }
+
+    /**
+     * @dataProvider dataIssue832
+     */
+    public function testIssue832(int $seed, string $expected): void
```
Comment (pimjansen) [inline test/Faker/Provider/ru_RU/PersonTest.php]: Please describe a valid test scenario instead of an issue number. Nobody will understand this in the future

**Review by pimjansen — DISMISSED** [review]

**Comment by pimjansen** [comment]
See my comments

File: src/Faker/Generator.php (hunk 1 above)
Comment (gam6itko) [reply src/Faker/Generator.php]: done

File: src/Faker/Generator.php (hunk 2 above)
Comment (gam6itko) [reply src/Faker/Generator.php]: done

File: test/Faker/Provider/ru_RU/PersonTest.php (hunk 3 above)
Comment (gam6itko) [reply test/Faker/Provider/ru_RU/PersonTest.php]: done

**Review by localheinz — APPROVED** [review]

**Comment by localheinz** [comment]
Thank you, @davydovks, @gam6itko, and @pimjansen!
